### ISSUE TITLE
Add option for TTA.

### ISSUE THREAD

**Issue by Naarty** [hmsintrepide/waifu2x-converter-gui-ps#1]
Hi I'm wondering if you can maybe add support for toggling TTA mode in the gui if it's a quick fix.

**Comment by hmsintrepide** [comment]
Hi
I don't see TTA option in @DeadSix27 waifu2x-converter-cpp build

**Comment by DeadSix27** [comment]
What is TTA?

**Comment by hmsintrepide** [comment]
I understood Test-Time Augmentation available in waifu2x-caffe

**Comment by DeadSix27** [comment]
@hmsintrepide Never used caffe one, what does it do?

**Comment by hmsintrepide** [comment]
Transalted doc from lltcggie/waifu2x-caffe
"If you use TTA mode, PSNR (image evaluation index) will rise about 0.15 instead of 8 times slower conversion."

**Comment by Naarty** [comment]
TTA does take some time to complete yes but if used with a gpu you can just
leave it working in the background to convert.
It's useful if you want the best quality out of waifu2x and have time to
spare.
